build:
	cd ./getExample && zip -r ../bin/getExample.zip . && cd ..
	cd ./postUser && zip -r ../bin/postUser.zip . && cd ..
	cd ./getUser && zip -r ../bin/getUser.zip . && cd ..
	find ./bin -type f -exec chmod 644 {} \;
	find ./bin -type d -exec chmod 755 {} \;
