build:
	cd ./getExample && zip ../bin/getExample.zip index.js && cd ..
	cd ./postUser && zip ../bin/postUser.zip index.js && cd ..
	cd ./getUser && zip ../bin/getUser.zip index.js && cd ..
	find ./bin -type f -exec chmod 644 {} \;
	find ./bin -type d -exec chmod 755 {} \;
